import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import NotAuthenticatePage from "@/components/ui/NotAuthenticatePage";
import HomePage from "@/components/ui/HomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {1==1 ? <HomePage/> : <NotAuthenticatePage />}
      </main>
    </>
  );
}
