import Head from "next/head";
import NotAuthenticatePage from "@/components/ui/NotAuthenticatePage";
import HomePage from "@/components/ui/HomePage";
import { auth } from "../database/config";
import { onAuthStateChanged } from "firebase/auth";
import { useEffect, useState } from "react";
import Skeleton from 'react-loading-skeleton';

export default function Home() {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const isUserActive = onAuthStateChanged(auth, (user) => {
      setUser(user);
      setLoading(false);
    });
    return isUserActive;
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? <Skeleton /> : user ? <HomePage /> : <NotAuthenticatePage />}
    </>
  );
}
